# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Package and Deploy Mule Application

on:
  push:
    branches: [ "develop" ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest
    environment: dev
    env:
      ## CloudHub 2.0 Properties -- Reference: https://docs.mulesoft.com/mule-runtime/4.4/mmp-concept
      CLOUDHUB2_APPLICATION_RUNTIME: 4.4.0
      CLOUDHUB2_APPLICATION_NAME: int-test-prc-api-v1-dev
      CLOUDHUB2_PRIVATE_SPACE_NAME: rjf-anypoint-sandbox-ps
      CLOUDHUB2_ENVIRONMENT: DEV
      CLOUDHUB2_REPLICAS_NUMBER: 1
      CLOUDHUB2_REPLICAS_SIZE: 0.1
      ANYPOINT_PLATFORM_BUSINESS_GROUP_ID: ${{ secrets.ANYPOINT_PLATFORM_BUSINESS_GROUP_ID }}
      ANYPOINT_PLATFORM_API_CLIENT_ID: ${{ secrets.ANYPOINT_PLATFORM_API_CLIENT_ID }}
      ANYPOINT_PLATFORM_API_CLIENT_SECRET: ${{ secrets.ANYPOINT_PLATFORM_API_CLIENT_SECRET }}
      ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID: ${{ secrets.ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID }}
      ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET }}

      ## Deployment properties
      M2_HOME: /home/runner/.m2
      
      ## --- Notes ---
      # To Skip MUnit Tests: Add -DskipMunitTests to the run command at the bottom
      # How to reference a GitHub Secret: ${{ secrets.SECRET_NAME }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "mulesoft-releases", "url": "https://repository.mulesoft.org/releases/" }]'
        plugin_repositories: '[{ "id": "mulesoft-releases", "url": "https://repository.mulesoft.org/releases/" }]'
        servers: '[{ "id": "anypoint-exchange-v3", "username": "~~~Client~~~", "password": "${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID}~?~${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET}" },
          { "id": "Repository", "username": "~~~Client~~~", "password": "${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID}~?~${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET}" }]'
    - name: Publish to Exchange
      run: |
        mvn clean deploy -s $M2_HOME/settings.xml \
          -DskipMunitTests
    - name: Deploy to Cloudhub
      run: |
        mvn clean deploy -DmuleDeploy -s $M2_HOME/settings.xml \
          -Dcloudhub2.application.runtime=${CLOUDHUB2_APPLICATION_RUNTIME} \
          -Dcloudhub2.application.name=${CLOUDHUB2_APPLICATION_NAME} \
          -Dcloudhub2.private-space.name=${CLOUDHUB2_PRIVATE_SPACE_NAME} \
          -Dcloudhub2.environment=${CLOUDHUB2_ENVIRONMENT} \
          -Dcloudhub2.replicas.number=${CLOUDHUB2_REPLICAS_NUMBER} \
          -Dcloudhub2.replicas.size=${CLOUDHUB2_REPLICAS_SIZE} \
          -Danypoint.platform.business-group.id=${ANYPOINT_PLATFORM_BUSINESS_GROUP_ID} \
          -Danypoint.platform.api.client-id=${ANYPOINT_PLATFORM_API_CLIENT_ID} \
          -Danypoint.platform.api.client-secret=${ANYPOINT_PLATFORM_API_CLIENT_SECRET} \
          -Danypoint.platform.connected-app.client-id=${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID} \
          -Danypoint.platform.connected-app.client-secret=${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET} \
          -DskipMunitTests