# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Mule Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy application'
        default: dev
        required: true
        type: environment
      replicas:
        description: 'Number of replicas'
        default: 1
        required: false
        type: choice
      replicaSize:
        description: 'Size of replica (Number of vCores)'
        default: 0.1
        required: false
        type: choice

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ## CloudHub 2.0 Properties -- Reference: https://docs.mulesoft.com/mule-runtime/4.4/mmp-concept
      CLOUDHUB2_APPLICATION_RUNTIME: 4.4.0
      CLOUDHUB2_APPLICATION_NAME: int-test-prc-api-v1-${{ inputs.environment }}
      CLOUDHUB2_PRIVATE_SPACE_NAME: >
        ${{ fromJson('{
          "dev": "rjf-anypoint-sandbox-ps",
          "testing": "rjf-anypoint-sandbox-ps",
          "staging": "rjf-anypoint-prod-ps",
          "prod": "rjf-anypoint-prod-ps"
        }')[github.event.inputs.environment] }}
      CLOUDHUB2_ENVIRONMENT: >
        ${{ fromJson('{
          "dev": "DEV",
          "testing": "TESTING",
          "staging": "STAGING",
          "prod": "PROD"
        }')[github.event.inputs.environment] }}
      CLOUDHUB2_REPLICAS_NUMBER: ${{ inputs.replicas }}
      CLOUDHUB2_REPLICAS_SIZE: ${{ inputs.replicaSize }}
      ANYPOINT_PLATFORM_BUSINESS_GROUP_ID: ${{ secrets.ANYPOINT_PLATFORM_BUSINESS_GROUP_ID }}
      ANYPOINT_PLATFORM_API_CLIENT_ID: ${{ secrets.ANYPOINT_PLATFORM_API_CLIENT_ID }}
      ANYPOINT_PLATFORM_API_CLIENT_SECRET: ${{ secrets.ANYPOINT_PLATFORM_API_CLIENT_SECRET }}
      ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID: ${{ secrets.ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID }}
      ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET }}

      ## Deployment properties
      M2_HOME: /home/runner/.m2
      
      ## --- Notes ---
      # To Skip MUnit Tests: Add -DskipMunitTests to the run command at the bottom
      # How to reference a GitHub Secret: ${{ secrets.SECRET_NAME }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Generate settings.xml
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        repositories: '[{ "id": "mulesoft-releases", "url": "https://repository.mulesoft.org/releases/" }]'
        plugin_repositories: '[{ "id": "mulesoft-releases", "url": "https://repository.mulesoft.org/releases/" }]'
        servers: '[{ "id": "anypoint-exchange-v3", "username": "~~~Client~~~", "password": "${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID}~?~${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET}" },
          { "id": "Repository", "username": "~~~Client~~~", "password": "${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID}~?~${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET}" }]'
    - name: Deploy to Cloudhub
      run: |
        mvn clean deploy -DmuleDeploy -s $M2_HOME/settings.xml \
          -Dcloudhub2.application.runtime=${CLOUDHUB2_APPLICATION_RUNTIME} \
          -Dcloudhub2.application.name=${CLOUDHUB2_APPLICATION_NAME} \
          -Dcloudhub2.private-space.name=${CLOUDHUB2_PRIVATE_SPACE_NAME} \
          -Dcloudhub2.environment=${CLOUDHUB2_ENVIRONMENT} \
          -Dcloudhub2.replicas.number=${CLOUDHUB2_REPLICAS_NUMBER} \
          -Dcloudhub2.replicas.size=${CLOUDHUB2_REPLICAS_SIZE} \
          -Danypoint.platform.business-group.id=${ANYPOINT_PLATFORM_BUSINESS_GROUP_ID} \
          -Danypoint.platform.api.client-id=${ANYPOINT_PLATFORM_API_CLIENT_ID} \
          -Danypoint.platform.api.client-secret=${ANYPOINT_PLATFORM_API_CLIENT_SECRET} \
          -Danypoint.platform.connected-app.client-id=${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_ID} \
          -Danypoint.platform.connected-app.client-secret=${ANYPOINT_PLATFORM_CONNECTED_APP_CLIENT_SECRET} \
          -DskipMunitTests